name:                mixml
version:             0.1.0.0
github:              "matsubara0507/mixml-hs"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall

description:         Please see the README on Github at <https://github.com/matsubara0507/mixml-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- extensible
- lens
- megaparsec
- transformers

library:
  source-dirs: src

executables:
  mixml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mixml

tests:
  mixml-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heredoc
    - mixml
    - tasty
    - tasty-hunit
